
CREATE TABLE [dbo].[GOODS_CODE](
	[ID_GOODS_CODE] [bigint] NOT NULL,
	[ID_CONTRACTOR] [bigint] NOT NULL,
	[ID_GOODS] [bigint] NOT NULL,
	[CODE] [varchar](64) NULL,
	[DATE_DELETED] [datetime] NULL,
	[ID_ES_SUPPLIER_CODE_GLOBAL] [uniqueidentifier] NULL,
	[PACKAGE_SIZE] [int] NULL,
 CONSTRAINT [PK_GOODS_CODE] PRIMARY KEY CLUSTERED 
(
	[ID_GOODS_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
