
CREATE TABLE [logs].[tables](
	[object_id] [int] NOT NULL,
	[TABLE_SCHEMA] [nvarchar](128) NOT NULL,
	[TABLE_NAME] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_tables] PRIMARY KEY CLUSTERED 
(
	[object_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


